<h3>Import libraries:</h3>

In [1]:
import roboticstoolbox as rtb
from spatialmath import SE3, base, SO3
import matplotlib.pyplot as plt
from math import pi, degrees, radians
import numpy as np
from spatialmath.base import tr2rpy
from mpl_toolkits.mplot3d import Axes3D
import spatialgeometry as sg
import time
import math
from IPython.display import HTML

# https://stackoverflow.com/questions/44116194/import-a-function-from-another-ipynb-file
from ipynb.fs.full.inverse_kinematics_dnb_robot import *

%matplotlib qt

<h3>Define the robot:</h3>

In [2]:
# Define the lenghts
l1 = 10.3
l2 = 16.525
l3 = 15.645
l4 = 8.8
l5 = 7.4

# Adjust the lenghts to plot the robot properly with the library (otherwise, the axes are too small)
# https://la.mathworks.com/matlabcentral/answers/485353-frames-not-appearing-using-robotics-system-toolbox
# scaleFactor = 50
scaleFactor = 1

l1 /= scaleFactor
l2 /= scaleFactor
l3 /= scaleFactor
l4 /= scaleFactor
l5 /= scaleFactor

# Notes:
# 1. For a revolute joint the theta parameter of the link is ignored, and q used instead.
# 2. For a prismatic joint the d parameter of the link is ignored, and q used instead.
# 3. The joint offset parameter is added to q before computation of the transformation matrix.

# Robot's links
link1 = rtb.RevoluteDH(d=l1, a=0.0, alpha=pi/2, offset=-pi/2, qlim=[0,pi])
link2 = rtb.RevoluteDH(d=0.0, a=l2, alpha=0.0, offset=0.0, qlim=[0,pi])
link3 = rtb.RevoluteDH(d=0.0, a=l3, alpha=0.0, offset=-radians(152), qlim=[0,pi])
link4 = rtb.RevoluteDH(d=0.0, a=l4, alpha=0.0, offset=0.0, qlim=[0,pi])

# https://petercorke.github.io/robotics-toolbox-python/arm_dh.html#roboticstoolbox.robot.DHLink.PrismaticDH

# Create the robot
robot = rtb.DHRobot(
    links=[link1, link2, link3, link4],
    name="D&B Robot",
    tool = SE3.Ty(-l5)
    )

# Home angles
qHome = [radians(90), radians(90), radians(0), radians(62)]

# Set home position
robot.addconfiguration_attr('home',qHome)

print(robot)
print(f'Robot is in 1:{scaleFactor} scale.')

DHRobot: D&B Robot, 4 joints (RRRR), dynamics, standard DH parameters
┌────────────┬──────┬───────┬───────┬──────┬────────┐
│     θⱼ     │  dⱼ  │  aⱼ   │  ⍺ⱼ   │  q⁻  │   q⁺   │
├────────────┼──────┼───────┼───────┼──────┼────────┤
│  q1 - 90°  │ 10.3 │     0 │ 90.0° │ 0.0° │ 180.0° │
│  q2        │    0 │ 16.52 │  0.0° │ 0.0° │ 180.0° │
│  q3 - 152° │    0 │ 15.64 │  0.0° │ 0.0° │ 180.0° │
│  q4        │    0 │   8.8 │  0.0° │ 0.0° │ 180.0° │
└────────────┴──────┴───────┴───────┴──────┴────────┘

┌──────┬──────────────────────────────────────┐
│ tool │ t = 0, -7.4, 0; rpy/xyz = 0°, 0°, 0° │
└──────┴──────────────────────────────────────┘

┌──────┬──────┬──────┬─────┬──────┐
│ name │ q0   │ q1   │ q2  │ q3   │
├──────┼──────┼──────┼─────┼──────┤
│ home │  90° │  90° │  0° │  62° │
└──────┴──────┴──────┴─────┴──────┘

Robot is in 1:1 scale.


In [3]:
# Plot home position
fig1 = plt.figure(figsize=(8, 8))  # Adjust this for larger or smaller axes
robot.plot(q=robot.home, backend='pyplot', fig = fig1)
plt.show()

<h3>Kinematics tests:</h3>

In [4]:
# Compute the forward kinematics
fk1 = robot.fkine(qHome)

# Get the real coordinates
fk1Escaled = SE3.Rt(fk1.R, fk1.t * scaleFactor)
# This SE3.Rt method takes a rotation matrix R and a position vector t and creates the desired SE(3) transformation

print(fk1Escaled)

   1         0         0         16.14     
   0         0        -1         0         
   0         1         0         5.611     
   0         0         0         1         



In [5]:
# Compute the inverse kinematics
ik1 = robot.ikine_LM(fk1, joint_limits = True)

for i in range(len(ik1.q)):
    print(f'q{i+1} = {round(degrees(ik1.q[i]),2)}°.')

q1 = 90.0°.
q2 = 90.0°.
q3 = 0.0°.
q4 = 62.0°.


In [6]:
# We'll use our own inverse kinematics function which gives us easier control of the end effector's orientation

pxHome = fk1.A[:,3][0]
pyHome = fk1.A[:,3][1]
pzHome = fk1.A[:,3][2]

# The orientation of the end effector is defined with respect to the base frame (only the pitch angle can be controlled)
pitchAngle = radians(0)

qList = inverse_kinematics(pxHome, pyHome, pzHome, pitchAngle, scaleFactor)

for index,q in enumerate(qList):
    print(f'q{index+1}: {q}°.')

q1: 90.0°.
q2: 90.0°.
q3: 0.0°.
q4: 62.0°.


In [7]:
# Traslation vector and pitch angle for frame1
pxFrame1 = 19/scaleFactor
pyFrame1 = -8.2/scaleFactor
pzFrame1 = 0.2/scaleFactor
pitchAngleFrame1 = radians(0)

# Its orientation needs to be determined; it's only known that the pitch angle, in the RPY convention, is equal to zero (parallel to the surface)
qFrame1 = inverse_kinematics(pxFrame1, pyFrame1, pzFrame1, pitchAngleFrame1, scaleFactor)
TFrame1 = robot.fkine([radians(i) for i in qFrame1])

print('Joint angles required to achieve the pose (orientation and position) of frame1:')
print(qFrame1)

print('\nHomogeneous transformation matrix (HTM) of {frame1} with respect to the base frame {0}:')
print(TFrame1)

# Extract RPY angles (mobile/current frame, ZYX convention)
rpyFrame1 = tr2rpy(TFrame1.R, order='zyx', unit='deg')

print('Euler angles in the ZYX convention with respect to the mobile/current frame:')
print(f'- Roll: {round(rpyFrame1[0],2)}°.')
print(f'- Pitch: {round(rpyFrame1[1],2)}°.')
print(f'- Yaw: {round(rpyFrame1[2],2)}°.')

# mobile/current frame, ZYX convention = fixed frame, XYZ convention
# https://mecademic.com/insights/academic-tutorials/space-orientation-euler-angles/
# https://bdaiinstitute.github.io/spatialmath-python/func_3d.html#spatialmath.base.transforms3d.tr2rpy

Joint angles required to achieve the pose (orientation and position) of frame1:
[66.66, 51.15, 16.45, 84.39]

Homogeneous transformation matrix (HTM) of {frame1} with respect to the base frame {0}:
   0.9182    0.0001603 -0.3962    19        
  -0.3962   -6.915e-05 -0.9182   -8.198     
  -0.0001745  1         0         0.1977    
   0         0         0         1         

Euler angles in the ZYX convention with respect to the mobile/current frame:
- Roll: 90.0°.
- Pitch: 0.01°.
- Yaw: -23.34°.


In [8]:
# Calculate the geometric jacobian with respect to the base frame
jacob1 = robot.jacob0(qFrame1)
print(jacob1)

[[ 3.09945364e+00  1.05213265e+01  2.41792369e+00 -6.06518951e+00]
 [ 2.54018707e+00 -1.28377804e+01 -2.95027184e+00  7.40054696e+00]
 [-6.82905448e-17 -4.00738858e+00 -1.44786665e+01 -6.37537300e+00]
 [-6.93889390e-17  7.73434764e-01  7.73434764e-01  7.73434764e-01]
 [ 0.00000000e+00  6.33875907e-01  6.33875907e-01  6.33875907e-01]
 [ 1.00000000e+00  6.12323400e-17  6.12323400e-17  6.12323400e-17]]


In [9]:
# Calculate the geometric jacobian with respect to the end-effector frame
jacob2 = robot.jacobe(qFrame1)
print(jacob2)

[[ 1.66533454e-16  2.13648723e+00  1.39646000e+01  7.40000000e+00]
 [-1.33226763e-15 -1.69411187e+01 -5.40112855e+00  8.80000000e+00]
 [ 4.00738858e+00 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00]
 [-9.93796042e-01  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.11217922e-01  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 6.12323400e-17  1.00000000e+00  1.00000000e+00  1.00000000e+00]]


In [10]:
# Calculate the analytical jacobian with respect to the base frame
jacob3 = robot.jacob0_analytical(qFrame1, representation='rpy/zyx')
print(jacob3)

[[ 3.09945364e+00  1.05213265e+01  2.41792369e+00 -6.06518951e+00]
 [ 2.54018707e+00 -1.28377804e+01 -2.95027184e+00  7.40054696e+00]
 [-6.82905448e-17 -4.00738858e+00 -1.44786665e+01 -6.37537300e+00]
 [ 3.95475620e-16  6.21724894e-15  6.21724894e-15  6.21724894e-15]
 [ 5.36678177e-17 -1.00000000e+00 -1.00000000e+00 -1.00000000e+00]
 [ 1.00000000e+00  6.21724894e-15  6.21724894e-15  6.21724894e-15]]


<h3>Trajectory test:</h3>

In [11]:
# https://petercorke.github.io/robotics-toolbox-python/arm_trajectory.html#roboticstoolbox.tools.trajectory.trapezoidal

# https://la.mathworks.com/help/robotics/ref/trapveltraj.html
# https://la.mathworks.com/help/robotics/ug/choose-trajectories-for-manipulator-paths.html
# https://la.mathworks.com/help/robotics/ug/design-a-trajectory-with-velocity-limits-using-a-trapezoidal-velocity-profile.html
# https://medium.com/mathworks/trajectory-planning-for-robot-manipulators-522404efb6f0

# https://youtu.be/f3JVWqsDhbE?si=McvOoeyu82TyQrwv
# https://youtu.be/Fd7wjZDoh7g?si=ZXw3PyyvvAwSEzFu

# Servomotor MG996R ----> Operating speed: 0.17 s/60º (4.8 V), 0.14 s/60º (6 V) 
# 0.14 s/60º (6 V) --------> 7,14 °/s (max speed)

# Set the time required to complete the trajectory
timeStepsTraj1 = 100
totalTime = 10 # Seconds
timeTraj1 = np.linspace(0, totalTime, timeStepsTraj1)

In [12]:
# Compute the trajectory using a trapezoidal velocity profile
# tg = rtb.tools.trapezoidal(pxHome*scaleFactor, pxFrame1*scaleFactor, timeTraj1)
# tg.plot()

# Generate the trajectory using a trapezoidal interpolator
q0Traj1 = [i*scaleFactor for i in [pxHome, pyHome, pzHome]]
q1Traj1 = [i*scaleFactor for i in [pxFrame1, pyFrame1, pzFrame1]]
Traj1 = rtb.tools.trajectory.mtraj(rtb.tools.trapezoidal, q0Traj1, q1Traj1, timeTraj1)

# Plot the position, velocity and acceleration data of the trajectory
Traj1.plot()

In [13]:
# Create a new figure for 3D plotting
fig2 = plt.figure()
ax = fig2.add_subplot(111, projection='3d')

# Plot the 3D trajectory in the workspace
ax.plot(Traj1.s[:,0], Traj1.s[:,1], Traj1.s[:,2])

# Add labels and title
ax.set_xlabel('X Label')
ax.set_ylabel('Y Label')
ax.set_zlabel('Z Label')
ax.set_title('Task-space trajectory')

# Show the plot
plt.show()

# We got a line in the cartesian space using a trapezoidal interpolator

In [14]:
# Let's repeat the same process using a quintic polynomial interpolator

# Generate the trajectory using a quintic polynomial interpolator
Traj1v2 = rtb.tools.trajectory.mtraj(rtb.tools.quintic, q0Traj1, q1Traj1, timeTraj1)

# Plot the position, velocity and acceleration data of the trajectory
Traj1v2.plot()

In [15]:
# Create a new figure for 3D plotting
fig3 = plt.figure()
ax = fig3.add_subplot(111, projection='3d')

# Plot the 3D trajectory in the workspace
ax.plot(Traj1v2.s[:,0], Traj1v2.s[:,1], Traj1v2.s[:,2])

# Add labels and title
ax.set_xlabel('X Label')
ax.set_ylabel('Y Label')
ax.set_zlabel('Z Label')
ax.set_title('Task-space trajectory')

# Show the plot
plt.show()

# We got a line in the cartesian space using a quintic polynomial interpolator

In [16]:
# Let's do it again with initial and final velocity different from zero (impractical in this case, it's just for testing)

# Set the velocities (they could be different for each axis)
dq0Traj1v3 = 0.5
dq1Traj1v3 = 1

Traj1v3x = rtb.tools.trajectory.quintic(q0Traj1[0], q1Traj1[0], timeTraj1, dq0Traj1v3, dq1Traj1v3)
Traj1v3y = rtb.tools.trajectory.quintic(q0Traj1[1], q1Traj1[1], timeTraj1, dq0Traj1v3, dq1Traj1v3)
Traj1v3z = rtb.tools.trajectory.quintic(q0Traj1[2], q1Traj1[2], timeTraj1, dq0Traj1v3, dq1Traj1v3)

# Create a new figure for 3D plotting
fig4 = plt.figure()
ax = fig4.add_subplot(111, projection='3d')

# Plot the 3D trajectory in the workspace
ax.plot(Traj1v3x.s, Traj1v3y.s, Traj1v3z.s)

# Add labels and title
ax.set_xlabel('X Label')
ax.set_ylabel('Y Label')
ax.set_zlabel('Z Label')
ax.set_title('Task-space trajectory')

# Show the plot
plt.show()

# We don't get a line in the cartesian space using a polynomial interpolator if the initial and final velocities are different from zero
# This also happens between viapoints

In [17]:
# We've only interpolated the position of the robot, but it's also required an orientation interpolation
# Position and orientation interpolation are two different issues, therefore they're done separately

# https://petercorke.github.io/robotics-toolbox-python/arm_trajectory.html#roboticstoolbox.tools.trajectory.ctraj
# We'll handle position and orientation interpolation through the ctraj function

# Set the time required to complete the trajectory
timeStepsTraj2 = 120
totalTime2 = 20 # Seconds
timeTraj2 = np.linspace(0, totalTime2, timeStepsTraj2)

# Compute the Cartesian trajectory between two poses (position + orientation)
traj2 = rtb.tools.trajectory.ctraj(fk1, TFrame1, timeTraj2)

# Afterwards, compute the inverse kinematics for each pose along the trajectory
# These joint configurations can be fed into a control system to execute and control the movements of the robotic arm

# qTraj2 = robot.ikine_LM(traj2)

# Plot the trajectory with the library
# robot.plot(qTraj2.q, backend='pyplot')
# plt.show()

In [18]:
# Plot the evolution of each position vector component in the trajectory

xTraj2 = traj2.x
yTraj2 = traj2.y
zTraj2 = traj2.z

fig6, (ax1, ax2, ax3) = plt.subplots(3,1, sharex=True)
fig6.suptitle('Evolution of each position vector component in the trajectory')

ax1.plot(timeTraj2, xTraj2)
ax1.set_ylabel('x')

ax2.plot(timeTraj2, yTraj2)
ax2.set_ylabel('y')

ax3.plot(timeTraj2, zTraj2)
ax3.set_ylabel('z')
ax3.set_xlabel('t')

plt.tight_layout()
plt.show()

In [19]:
# Plot the evolution of each position vector component's velocity in the trajectory

# Get the time step
deltaT = timeTraj2[5] - timeTraj2[4]

deltaX = np.hstack((0,np.diff(xTraj2, axis = 0)))
deltaY = np.hstack((0,np.diff(yTraj2, axis = 0)))
deltaZ = np.hstack((0,np.diff(zTraj2, axis = 0)))
# Add zero at the start of the array to match the position array size

velX = deltaX/deltaT
velY = deltaY/deltaT
velZ = deltaZ/deltaT

fig7, (ax1, ax2, ax3) = plt.subplots(3,1, sharex=True)
fig7.suptitle('Evolution of each position vector components velocity in the trajectory')

ax1.plot(timeTraj2, velX)
ax1.set_ylabel('x')

ax2.plot(timeTraj2, velY)
ax2.set_ylabel('y')

ax3.plot(timeTraj2, velZ)
ax3.set_ylabel('z')
ax3.set_xlabel('t')

plt.tight_layout()
plt.show()

<h3>Resolved-Rate Motion Control:</h3>

In [20]:
# https://youtu.be/sc5DZOkNvTc?si=JpxpIKR4r8iLLvUk
# https://youtu.be/1GaxV8x4YHA?si=SVk1Yh55wbxU7_Xb
# https://youtu.be/AgQ_Bybl_9k?si=KLwMJ_HOi7Fy8zhD
# https://youtu.be/5lZD93jh2m0?si=QN1pOT8hGjsfnb5M
# https://youtu.be/FU9jC1lHt_c?si=89MTK9BMjQouzqFE

<h4>Method 1 (RRMC without velocity profile nor cartesian interpolation):</h4>

In [21]:
# Based on the following notebook:
# https://github.com/jhavl/dkt/blob/main/Part%201/3%20Resolved-Rate%20Motion%20Control.ipynb
# https://arxiv.org/pdf/2207.01796

In [22]:
# https://youtu.be/-TUTqVOGSa8?si=3OldHsu_qE9i22FQ
# https://youtu.be/s0NC85TAPaA?si=zr1ObUN9i66GhVMp
# https://youtu.be/axEadpYSOv8?si=grupjc4v4PHLdA9d

def error(currentPose, desiredPose):

    # Returns the error between the desired and the current pose (position: vector, rotation: angle-axis notation)
    # currentPose and desiredPose --> np.ndarray with shape = (4,4)
    # currentPose and desiredPose are the poses of the end effector relative to the base frame
    
    # Error array
    e = np.empty(6)

    # The position error
    e[:3] = desiredPose[:3, -1] - currentPose[:3, -1]

    # The rotation error expressed as rotation matrix
    R = desiredPose[:3, :3] @ currentPose[:3, :3].T

    # Transform the rotation matrix to its Euler vector equivalent
    
    li = np.array([R[2, 1] - R[1, 2], R[0, 2] - R[2, 0], R[1, 0] - R[0, 1]])

    if np.linalg.norm(li) < 1e-6:
        # If li is a zero vector (or very close to it)

        # Diagonal matrix case
        if np.trace(R) > 0:
            # (1,1,1) case
            a = np.zeros((3,))
        else:
            a = np.pi / 2 * (np.diag(R) + 1)
    else:
        # Non-diagonal matrix case
        ln = np.linalg.norm(li)
        a = math.atan2(ln, np.trace(R) - 1) * li / ln
    
    # Append the rotation error expressed in the angle-axis representation in the error array
    e[3:] = a

    # Return the error
    return e

In [23]:
def p_servo(currentPose, desiredPose, gain, threshold = 0.001):
    
    # Position-based servoing

    # Returns the end-effector velocity in the cartesian space which will cause the robot to approach the desired pose

    # currentPose: The current pose of the end-effecor in the base frame (ndarray)
    # desiredPose: The desired pose of the end-effecor in the base frame (ndarray)
    # gain: The gain for the proportional controller. A vector corresponding to each Cartesian axis (array-like)
    # threshold: The threshold or tolerance of the final error between the robot's pose and desired pose (float)

    # v: The velocity of the end-effector which will casue the robot to approach desiredPose (ndarray(6))
    # arrived: True if the robot is within the threshold of the final pose (bool)
    
    if isinstance(currentPose, SE3):
        currentPose = currentPose.A

    if isinstance(desiredPose, SE3):
        desiredPose = desiredPose.A

    # Calculate the pose error vector
    e = error(currentPose, desiredPose)

    # Construct our gain diagonal matrix
    if base.isscalar(gain):
        k = gain * np.eye(6)
    else:
        k = np.diag(gain)

    # Calculate our desired end-effector velocity
    v = k @ e

    # Check if we have arrived
    arrived = True if np.sum(np.abs(e)) < threshold else False

    # Tuple[np.ndarray, bool]
    return v, arrived

In [24]:
# https://github.com/petercorke/robotics-toolbox-python/blob/master/roboticstoolbox/examples/RRMC.py

env = rtb.backends.PyPlot.PyPlot()
env.launch('Resolved-Rate Motion Control Example')

arrived = False

env.add(robot)

# Set the current pose
robot.q = qHome

# Desired pose
pxFrame2 = 37/scaleFactor
pyFrame2 = -8.2/scaleFactor
pzFrame2 = 0.2/scaleFactor
pitchAngleFrame2 = radians(0)

# Its orientation needs to be determined; it's only known that the pitch angle, in the RPY convention, is equal to zero (parallel to the surface)
qFrame2 = inverse_kinematics(pxFrame2, pyFrame2, pzFrame2, pitchAngleFrame2, scaleFactor)
TFrame2 = robot.fkine([radians(i) for i in qFrame2])

# Proportional control gain
gain = 3

# Time step
dt = 0.05

# Set the maximum end-effector velocity
vMax = 1.0

# Lists to save the values obtained in each time step
posesObtained = []
cartesianVelocitiesObtained = []
jointPositionsObtained = []
jointVelocitiesObtained = []

while not arrived:

    start = time.time()
    
    # HTM involved
    currentPose = robot.fkine(robot.q)
    desiredPose = TFrame2
    
    # Cartesian velocity required (both linear and angular velocities)
    v, arrived = p_servo(currentPose, desiredPose, gain)
    
    # Calculate the magnitude of the end-effector velocity
    vNorm = np.linalg.norm(v)

    # If the end-effector velocity exceeds the maximum allowed
    if vNorm > vMax:
        v = (vMax / vNorm) * v

    # Map it to joint velocities using the geometric jacobian relative to the base frame
    qd = np.linalg.pinv(robot.jacob0(robot.q)) @ v
    
    # Apply the calculated joint velocity to the robot's actuators for movement
    robot.qd = qd
    
    # Append the values obtained in this iteration
    posesObtained.append(currentPose)
    cartesianVelocitiesObtained.append(v)
    jointPositionsObtained.append(robot.q)
    jointVelocitiesObtained.append(qd)
    
    env.step(dt)
    stop = time.time()
    
    if stop - start < dt:
        time.sleep(dt - (stop - start))

# robot.plot(q=[radians(i) for i in qFrame2], backend='pyplot')

In [25]:
# Create a new figure for 3D plotting
fig5 = plt.figure()
ax1 = fig5.add_subplot(111, projection='3d')
# ax2 = fig5.add_subplot(122, projection='3d')

# Plot the 3D trajectory for the translational motion in the workspace
for htm in posesObtained:
    ax1.scatter(htm.A[0,3], htm.A[1,3], htm.A[2,3])

# Plot the desired pose
ax1.scatter(TFrame2.A[0,3], TFrame2.A[1,3], TFrame2.A[2,3], marker="*", linewidths=3, c='r')

# Add labels and title
ax1.set_xlabel('X Label')
ax1.set_ylabel('Y Label')
ax1.set_zlabel('Z Label')
ax1.set_title('Task-space trajectory')

# for vel in cartesianVelocitiesObtained:
#     ax2.scatter(vel[0], vel[1], vel[2])

# Show the plot
plt.show()

In [26]:
# Time spent in the trajectory
t = np.arange(0, len(cartesianVelocitiesObtained)*dt, dt)

fig8, (ax1, ax2) = plt.subplots(2,1, sharex=True)
fig8.suptitle('Trajectory')

ax1.plot(t, [pose.x for pose in posesObtained], label='x')
ax1.plot(t, [pose.y for pose in posesObtained], label='y')
ax1.plot(t, [pose.z for pose in posesObtained], label='z')
ax1.set_ylabel('Position')
ax1.legend()

ax2.plot(t, [velocity[0] for velocity in cartesianVelocitiesObtained], label='vx')
ax2.plot(t, [velocity[1] for velocity in cartesianVelocitiesObtained], label='vy')
ax2.plot(t, [velocity[2] for velocity in cartesianVelocitiesObtained], label='vz')
ax2.set_ylabel('Velocity')
ax2.set_xlabel('Time')
ax2.legend()

plt.tight_layout()
plt.show()

<h4>Method 2 (RRMC with position and velocity profiles):</h4>

In [27]:
# https://www.youtube.com/watch?v=5lZD93jh2m0

In [28]:
def rotation_matrix_to_angle_axis_repr(R):
    
    # Transform the rotation matrix to its Euler vector equivalent
    
    li = np.array([R[2, 1] - R[1, 2], R[0, 2] - R[2, 0], R[1, 0] - R[0, 1]])

    if np.linalg.norm(li) < 1e-6:
        # If li is a zero vector (or very close to it)

        # Diagonal matrix case
        if np.trace(R) > 0:
            # (1,1,1) case
            a = np.zeros((3,))
        else:
            a = np.pi / 2 * (np.diag(R) + 1)
    else:
        # Non-diagonal matrix case
        ln = np.linalg.norm(li)
        a = math.atan2(ln, np.trace(R) - 1) * li / ln

    return a

def pose_error(currentPose, desiredPose):

    # Returns the error between the desired and the current pose (position: vector, orientation: angle-axis notation)
    # currentPose and desiredPose --> np.ndarray with shape = (4,4)
    # currentPose and desiredPose are the poses of the end effector relative to the base frame
    
    if isinstance(currentPose, SE3):
        currentPose = currentPose.A

    if isinstance(desiredPose, SE3):
        desiredPose = desiredPose.A

    # Error array
    e = np.empty(6)

    # The position error
    e[:3] = desiredPose[:3, -1] - currentPose[:3, -1]

    # The rotation error expressed as rotation matrix
    R = desiredPose[:3, :3] @ currentPose[:3, :3].T

    # Transform the rotation matrix to its Euler vector equivalent
    a = rotation_matrix_to_angle_axis_repr(R)
    
    # Append the rotation error expressed in the angle-axis representation in the error array
    e[3:] = a

    # Return the error
    # e.shape = (6,)
    return e

In [29]:
# Get the HTM for the initial configuration of the robot in the trajectory
T0 = robot.fkine(qHome)

# Get the desired pose
pxT1 = 37/scaleFactor
pyT1 = -8.2/scaleFactor
pzT1 = 0.2/scaleFactor
pitchAngleT1 = radians(0)

# Its orientation needs to be determined; it's only known that the pitch angle, in the RPY convention, is equal to zero (parallel to the surface)
qT1 = inverse_kinematics(pxT1, pyT1, pzT1, pitchAngleT1, scaleFactor)
T1 = robot.fkine([radians(i) for i in qT1])

# type(T0) and type(T1) ----> spatialmath.pose3d.SE3

# Set time step in seconds
dt = 0.2

# Total time in seconds
totalTime = 8

# Time array
trajTime = np.arange(0, totalTime, dt)

# Number of steps
stepsNum = len(trajTime)

# https://petercorke.github.io/robotics-toolbox-python/arm_trajectory.html#roboticstoolbox.tools.trajectory.trapezoidal
# Generate the trapezoidal trajectory for the translational components
x = rtb.tools.trajectory.trapezoidal(T0.A[0,3], T1.A[0,3], trajTime)
y = rtb.tools.trajectory.trapezoidal(T0.A[1,3], T1.A[1,3], trajTime)
z = rtb.tools.trajectory.trapezoidal(T0.A[2,3], T1.A[2,3], trajTime)

# Velocities of the translational components along the trajectory (linear velocities)
vx = x.qd
vy = y.qd
vz = z.qd

# Transform the initial and final rotation matrices to angle-axis representation
angAxisT0 = rotation_matrix_to_angle_axis_repr(T0.R)
angAxisT1 = rotation_matrix_to_angle_axis_repr(T1.R)

# Generate the trapezoidal trajectory for the orientation components in angle-axis representation form
angx = rtb.tools.trajectory.trapezoidal(angAxisT0[0], angAxisT1[0], trajTime)
angy = rtb.tools.trajectory.trapezoidal(angAxisT0[1], angAxisT1[1], trajTime)
angz = rtb.tools.trajectory.trapezoidal(angAxisT0[2], angAxisT1[2], trajTime)
angs = [np.array([angx.q[i], angy.q[i], angz.q[i]])for i in range(len(angx))]

# Get the angular velocities
wx = angx.qd
wy = angy.qd
wz = angz.qd

# Transform the trajectory represented in angle-axis form to rotation matrix
rotMatrix = [(SO3.AngleAxis(np.linalg.norm(angs[i]),angs[i]/np.linalg.norm(angs[i]))).R for i in range(len(trajTime))]

# https://www.euclideanspace.com/physics/kinematics/angularvelocity/

In [30]:
# Plot all the calculated parameters

fig9, axes = plt.subplots(2,2) 
# plt.subplots(2, 2) returns a 2x2 array of axes

# Unpack the axes array into individual variables
(ax1, ax2), (ax3, ax4) = axes

fig9.suptitle('Trajectory')

ax1.plot(trajTime, x.q, label='x')
ax1.plot(trajTime, y.q, label='y')
ax1.plot(trajTime, z.q, label='z')
ax1.set_ylabel('Position')
ax1.legend()

ax2.plot(trajTime, x.qd, label='vx')
ax2.plot(trajTime, y.qd, label='vy')
ax2.plot(trajTime, z.qd, label='vz')
ax2.set_ylabel('Linear velocity')
ax2.set_xlabel('Time')
ax2.legend()

ax3.plot(trajTime, angx.q, label='x-axis rotation')
ax3.plot(trajTime, angy.q, label='y-axis rotation')
ax3.plot(trajTime, angz.q, label='z-axis rotation')
ax3.set_ylabel('Angular position')
ax3.set_xlabel('Time')
ax3.legend()

ax4.plot(trajTime, wx, label='wx')
ax4.plot(trajTime, wy, label='wy')
ax4.plot(trajTime, wz, label='wz')
ax4.set_ylabel('Angular velocity')
ax4.set_xlabel('Time')
ax4.legend()


plt.tight_layout()
plt.show()

In [31]:
# Create the homogeneous transformation matrices using the rotation matrices and translation vectors from the trajectory
XRef = [SE3.Rt(rotMatrix[j], np.array([x.q[j], y.q[j], z.q[j]])) for j in range(len(trajTime))]

# Organize the velocities to ease its manipulation
XdRef = [np.array([vx[i], vy[i], vz[i], wx[i], wy[i], wz[i]]) for i in range(len(trajTime))]

In [32]:
# https://github.com/petercorke/robotics-toolbox-python/blob/master/roboticstoolbox/examples/RRMC.py

env2 = rtb.backends.PyPlot.PyPlot()
env2.launch('Resolved-Rate Motion Control Example')

arrived = False

env2.add(robot)

# Set the starting pose in the robot
robot.q = qHome

# Proportional control gain
gain = 2

# Construct our gain diagonal matrix
if base.isscalar(gain):
    kp = gain * np.eye(6)
else:
    kp = np.diag(gain)
    
threshold = 5

i = 0 # Auxiliar variable

# Lists to save the values obtained in each time step
posesObtained = []
cartesianVelocitiesObtained = []
jointPositionsObtained = []
jointVelocitiesObtained = []

while not arrived:
    
    start = time.time()
    
    # Current robot's pose
    currentPose = robot.fkine(robot.q)

    if i < len(XRef):
        # Desired pose  in this specific time step:
        desiredPose = XRef[i]
        actualXdRef = XdRef[i]
    else:
        # If all trajectory points have been processed, ensure the robot's final pose is achieved correctly
        desiredPose = XRef[-1]
        actualXdRef = XdRef[-1]
        
    # Compute the position error
    poseError = pose_error(currentPose, desiredPose)
    
    # Compute the combined term (feedforward + feedback)
    referenceVelocityAdjusted = actualXdRef + (kp @ poseError)
    
    # Use this term to calculate joint velocities using the geometric jacobian relative to the base frame
    qd = np.linalg.pinv(robot.jacob0(robot.q)) @ referenceVelocityAdjusted
    print(qd)
    
    # Apply the calculated joint velocity to the robot's actuators for movement
    robot.qd = qd
    
    if i >= len(XRef):
        # Check if the robotic arm has reached the desired point
        arrived = True if np.sum(np.abs(poseError)) < threshold else False

    # Update the auxiliar variable
    i += 1
    
    # Append the values obtained in this iteration
    posesObtained.append(currentPose)
    cartesianVelocitiesObtained.append(referenceVelocityAdjusted)
    jointPositionsObtained.append((robot.q).copy())
    jointVelocitiesObtained.append(qd)
    
    env2.step(dt)
    stop = time.time()
    
    # Complete the time step
    if stop - start < dt:
        time.sleep(dt - (stop - start))

[0. 0. 0. 0.]
[-0.00899658 -0.03474035  0.01862375  0.01865042]
[-0.01721994 -0.0659935   0.03678731  0.03326072]
[-0.02469311 -0.09400848  0.05504984  0.04392669]
[-0.03139947 -0.11885539  0.07376901  0.05060426]
[-0.03730716 -0.14057002  0.09317051  0.05324946]
[-0.04238694 -0.15924867  0.11338866  0.05191161]
[-0.04662356 -0.17509602  0.13449447  0.04677649]
[-0.05002152 -0.18843352  0.15651923  0.03816524]
[-0.05260647 -0.19967906  0.179476    0.02650098]
[-0.05442355 -0.20931111  0.2033795   0.01225813]
[-0.05553376 -0.21782998  0.22826396 -0.00409104]
[-0.05600945 -0.22572577  0.25419899 -0.02212255]
[-0.0559296  -0.23345842  0.28130419 -0.04149412]
[-0.0506365  -0.22031812  0.28542943 -0.0612949 ]
[-0.04645144 -0.21179866  0.29024347 -0.07615251]
[-0.04298021 -0.20620087  0.29570739 -0.08813176]
[-0.04000079 -0.2025929   0.30179016 -0.09837628]
[-0.03738287 -0.2004528   0.3084946  -0.10755652]
[-0.03504612 -0.19948557  0.31586079 -0.116095  ]
[-0.03293809 -0.19952832  0.32396468

In [35]:
# Create a new figure for 3D plotting
fig10 = plt.figure()
ax1 = fig10.add_subplot(111, projection='3d')

# Plot the 3D trajectory for the translational motion in the workspace
for htm in posesObtained:
    ax1.scatter(htm.A[0,3], htm.A[1,3], htm.A[2,3])

# Plot the desired pose
ax1.scatter(T1.A[0,3], T1.A[1,3], T1.A[2,3], marker="*", linewidths=3, c='r')

# Add labels and title
ax1.set_xlabel('X Label')
ax1.set_ylabel('Y Label')
ax1.set_zlabel('Z Label')
ax1.set_title('Task-space trajectory')

# Show the plot
plt.show()

In [34]:
# Plot the obtained parameters

# Ignore the time in these plots

fig11, axes = plt.subplots(2,2)
(ax1, ax2), (ax3, ax4) = axes
fig11.suptitle('Trajectory')

ax1.plot([pose.x for pose in posesObtained], label='x')
ax1.plot([pose.y for pose in posesObtained], label='y')
ax1.plot([pose.z for pose in posesObtained], label='z')
ax1.set_ylabel('Cartesian positions')
ax1.set_xlabel('Time')
ax1.legend()

ax2.plot([velocity[0] for velocity in cartesianVelocitiesObtained], label='vx')
ax2.plot([velocity[1] for velocity in cartesianVelocitiesObtained], label='vy')
ax2.plot([velocity[2] for velocity in cartesianVelocitiesObtained], label='vz')
ax2.plot([velocity[3] for velocity in cartesianVelocitiesObtained], label='wx')
ax2.plot([velocity[4] for velocity in cartesianVelocitiesObtained], label='wy')
ax2.plot([velocity[5] for velocity in cartesianVelocitiesObtained], label='wz')
ax2.set_ylabel('Cartesian velocities')
ax2.set_xlabel('Time')
ax2.legend()

ax3.plot([q[0] for q in jointPositionsObtained], label='q1')
ax3.plot([q[1] for q in jointPositionsObtained], label='q2')
ax3.plot([q[2] for q in jointPositionsObtained], label='q3')
ax3.plot([q[3] for q in jointPositionsObtained], label='q4')
ax3.set_ylabel('Joint positions')
ax3.set_xlabel('Time')
ax3.legend()

ax4.plot([qd[0] for qd in jointVelocitiesObtained], label='qd1')
ax4.plot([qd[1] for qd in jointVelocitiesObtained], label='qd2')
ax4.plot([qd[2] for qd in jointVelocitiesObtained], label='qd3')
ax4.plot([qd[3] for qd in jointVelocitiesObtained], label='qd4')
ax4.set_ylabel('Joint velocities')
ax4.set_xlabel('Time')
ax4.legend()

plt.tight_layout()
plt.show()